- name: Send file to remote server
  hosts: 13.233.216.211
  become: yes

  tasks:
    - name: Copy WAR file
      copy:
        src: ./target/facebookapp-1.0.0.war
        dest: /opt/tomcat/webapps/
